-- Migration: Remove Grid Cell System & Add Polygon-Based Mapping Tables
-- Date: 2026-08-14

-- 1. Remove grid_cell_id columns from existing tables
ALTER TABLE IF EXISTS public.monitoring_sites DROP COLUMN IF EXISTS current_grid_cell_id;
ALTER TABLE IF EXISTS public.site_locations DROP COLUMN IF EXISTS grid_cell_id;
ALTER TABLE IF EXISTS public.sensor_data DROP COLUMN IF EXISTS grid_cell_id;
ALTER TABLE IF EXISTS public.inspection_photos DROP COLUMN IF EXISTS grid_cell_id;

-- 2. Create odor_zones table for spatial dispersion polygons
CREATE TABLE IF NOT EXISTS public.odor_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT REFERENCES public.monitoring_sites(id) ON DELETE CASCADE,
    zone_name TEXT NOT NULL,
    severity_level TEXT NOT NULL CHECK (severity_level IN ('LOW', 'MODERATE', 'HIGH', 'CRITICAL')),
    ammonia_ppm NUMERIC DEFAULT 0,
    coordinates JSONB NOT NULL, -- Array of [lat, lng] vertices
    created_at TIMESTAMPTZ DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id) DEFAULT auth.uid()
);

-- Enable RLS on odor_zones
ALTER TABLE public.odor_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.odor_zones FORCE ROW LEVEL SECURITY;

-- RLS Policies for odor_zones
CREATE POLICY "Enable read access for authenticated users on odor_zones"
ON public.odor_zones FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Enable insert for authenticated users on odor_zones"
ON public.odor_zones FOR INSERT
TO authenticated
WITH CHECK (created_by = auth.uid());